# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish', models.CharField(max_length=50)),
                ('happie', models.IntegerField()),
                ('angrie', models.IntegerField()),
                ('dehydratie', models.IntegerField()),
                ('depressie', models.IntegerField()),
                ('excitie', models.IntegerField()),
                ('unwellie', models.IntegerField()),
            ],
        ),

        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='餐厅名称')),
                ('latitude', models.DecimalField(max_digits=6, decimal_places=2, verbose_name='纬度')),
                ('longitude', models.DecimalField(max_digits=6, decimal_places=2, verbose_name='经度')),
                ('rating', models.DecimalField(max_digits=6, decimal_places=2, verbose_name='评分')),
                ('cost', models.IntegerField(verbose_name='花费')),
                ('count', models.IntegerField(verbose_name='数量')),

                # 现有菜品
                ('chholebature', models.IntegerField(verbose_name='炒饼')),
                ('rajmachawal', models.IntegerField(verbose_name='拉吉玛饭')),
                ('dosa', models.IntegerField(verbose_name='薄饼')),
                ('idli', models.IntegerField(verbose_name='印度小圆饼')),
                ('noodles', models.IntegerField(verbose_name='面条')),
                ('chillypaneer', models.IntegerField(verbose_name='辣椒炒干酪')),
                ('alootikki', models.IntegerField(verbose_name='炸土豆饼')),
                ('vadapao', models.IntegerField(verbose_name='炸馅饼')),
                ('garlicbread', models.IntegerField(verbose_name='蒜香面包')),
                ('pasta', models.IntegerField(verbose_name='意大利面')),
                ('springroll', models.IntegerField(verbose_name='春卷')),
                ('ham', models.IntegerField(verbose_name='火腿')),
                ('icecream', models.IntegerField(verbose_name='冰激凌')),
                ('pastries', models.IntegerField(verbose_name='蛋糕')),
                ('chocolates', models.IntegerField(verbose_name='巧克力')),
                ('tea', models.IntegerField(verbose_name='茶')),
                ('softdrinks', models.IntegerField(verbose_name='软饮料')),
                ('juices', models.IntegerField(verbose_name='果汁')),

                # 新增菜品
                ('chili_chicken_noodles', models.IntegerField(verbose_name='辣子鸡面')),
                ('spicy_wonton', models.IntegerField(verbose_name='麻辣抄手')),
                ('sour_cabbage_wonton', models.IntegerField(verbose_name='酸菜抄手')),
                ('cumin_beef_noodles', models.IntegerField(verbose_name='孜然牛肉盖面')),
                ('sour_cabbage_beef_noodles', models.IntegerField(verbose_name='酸菜牛肉面')),
                ('sichuan_style_spicy_fish_noodles', models.IntegerField(verbose_name='川香麻辣口味五谷鱼粉')),

                ('cantonese_stone_ground_rice_noodles', models.IntegerField(verbose_name='广式石磨肠粉')),
                ('honey_glazed_roast_pork_rice', models.IntegerField(verbose_name='蜜汁叉烧饭')),
                ('crispy_roast_duck_rice', models.IntegerField(verbose_name='脆皮烧鸭饭')),
                ('beef_ball_noodles', models.IntegerField(verbose_name='牛筋丸面')),
                ('zhanjiang_boiled_chicken_rice', models.IntegerField(verbose_name='湛江白切鸡饭')),
                ('rose_sauce_chicken_rice', models.IntegerField(verbose_name='玫瑰豉油鸡饭')),
                ('salt_baked_chicken_leg_rice', models.IntegerField(verbose_name='盐焗鸡腿饭')),
                ('signature_roast_duck_rice', models.IntegerField(verbose_name='招牌烧鸭饭')),
                ('kung_fu_duck_leg_rice', models.IntegerField(verbose_name='功夫鸭腿饭')),
                ('crispy_duck_leg_rice', models.IntegerField(verbose_name='脆皮鸭腿饭')),
                ('secret_recipe_chicken_steak_rice', models.IntegerField(verbose_name='秘制鸡排饭')),

                ('spicy_shrimp', models.IntegerField(verbose_name='香辣虾')),
                ('chili_chicken', models.IntegerField(verbose_name='辣子鸡')),
                ('chili_pepper_fried_pork', models.IntegerField(verbose_name='辣椒炒肉')),
                ('salivating_chicken', models.IntegerField(verbose_name='口水鸡')),
                ('hot_dry_noodles', models.IntegerField(verbose_name='热干面')),
                ('pork_mince_with_eggplant_over_rice', models.IntegerField(verbose_name='肉沫茄子盖饭')),
                ('sausage_fried_with_dried_radish', models.IntegerField(verbose_name='腊肠炒萝卜干')),
                ('garlic_fragrant_chicken_steak', models.IntegerField(verbose_name='蒜香鸡排')),
                ('scallion_oil_mixed_noodles', models.IntegerField(verbose_name='葱油拌面')),
                ('nanchang_mixed_noodles', models.IntegerField(verbose_name='南昌拌面')),

                ('seaweed_braised_chicken', models.IntegerField(verbose_name='海苔碎焖鸡')),
                ('curry_chicken_rice', models.IntegerField(verbose_name='咖喱鸡饭')),
                ('xinjiang_style_large_plate_chicken', models.IntegerField(verbose_name='新疆大盘鸡')),
                ('authentic_beef_patty', models.IntegerField(verbose_name='正点牛肉饼')),
                ('curry_chicken_with_chicken_steak', models.IntegerField(verbose_name='咖喱鸡拼鸡扒')),
                ('xinjiang_style_large_plate_chicken_with_coca_cola_chicken',models.IntegerField(verbose_name='新疆大盘鸡拼可乐鸡')),
                ('seaweed_braised_chicken_with_chicken_steak', models.IntegerField(verbose_name='海苔焖鸡拼鸡扒')),
                ('signature_chicken_leg_rice', models.IntegerField(verbose_name='招牌鸡腿饭')),
                ('american_coca_cola_chicken', models.IntegerField(verbose_name='美式可乐鸡')),
                ('signature_beggars_chicken', models.IntegerField(verbose_name='招牌叫花鸡')),
                ('black_pepper_chicken_steak_rice', models.IntegerField(verbose_name='黑椒鸡扒饭')),

                ('chaoshan_pork_roll_rice', models.IntegerField(verbose_name='潮汕肉卷饭')),
                ('chaoshan_mixed_rice_noodles', models.IntegerField(verbose_name='潮汕拌粿条')),
                ('longjiang_pork_trotter_rice', models.IntegerField(verbose_name='隆江猪脚饭')),
                ('pork_stew_rice', models.IntegerField(verbose_name='卤肉饭')),
                ('original_pork_offal_noodles', models.IntegerField(verbose_name='原味猪杂面')),
                ('original_seafood_pork_offal_noodles', models.IntegerField(verbose_name='原味海鲜猪杂面')),
                ('lemon_flavored_pork_offal_noodles', models.IntegerField(verbose_name='柠檬味猪杂面')),
                ('tomato_flavored_pork_offal_noodles', models.IntegerField(verbose_name='番茄味猪杂面')),
            ],
        ),



        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('yesno', models.IntegerField()),
            ],
        ),
    ]
