# Generated by Django 3.2.25 on 2024-12-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mooddata',
            options={'verbose_name': '情绪数据', 'verbose_name_plural': '情绪数据'},
        ),
        migrations.AlterModelOptions(
            name='restaurants',
            options={'verbose_name': '餐厅', 'verbose_name_plural': '餐厅'},
        ),
        migrations.AlterModelOptions(
            name='trainingdata',
            options={'verbose_name': '训练数据', 'verbose_name_plural': '训练数据'},
        ),
        migrations.AddField(
            model_name='restaurants',
            name='american_coca_cola_chicken',
            field=models.IntegerField(default=0, verbose_name='美式可乐鸡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='authentic_beef_patty',
            field=models.IntegerField(default=0, verbose_name='正点牛肉饼'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='beef_ball_noodles',
            field=models.IntegerField(default=0, verbose_name='牛筋丸面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='black_pepper_chicken_steak_rice',
            field=models.IntegerField(default=0, verbose_name='黑椒鸡扒饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='cantonese_stone_ground_rice_noodles',
            field=models.IntegerField(default=0, verbose_name='广式石磨肠粉'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='chaoshan_mixed_rice_noodles',
            field=models.IntegerField(default=0, verbose_name='潮汕拌粿条'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='chaoshan_pork_roll_rice',
            field=models.IntegerField(default=0, verbose_name='潮汕肉卷饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='chili_chicken',
            field=models.IntegerField(default=0, verbose_name='辣子鸡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='chili_chicken_noodles',
            field=models.IntegerField(default=0, verbose_name='辣子鸡面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='chili_pepper_fried_pork',
            field=models.IntegerField(default=0, verbose_name='辣椒炒肉'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='crispy_duck_leg_rice',
            field=models.IntegerField(default=0, verbose_name='脆皮鸭腿饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='crispy_roast_duck_rice',
            field=models.IntegerField(default=0, verbose_name='脆皮烧鸭饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='cumin_beef_noodles',
            field=models.IntegerField(default=0, verbose_name='孜然牛肉盖面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='curry_chicken_rice',
            field=models.IntegerField(default=0, verbose_name='咖喱鸡饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='curry_chicken_with_chicken_steak',
            field=models.IntegerField(default=0, verbose_name='咖喱鸡拼鸡扒'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='garlic_fragrant_chicken_steak',
            field=models.IntegerField(default=0, verbose_name='蒜香鸡排'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='honey_glazed_roast_pork_rice',
            field=models.IntegerField(default=0, verbose_name='蜜汁叉烧饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='hot_dry_noodles',
            field=models.IntegerField(default=0, verbose_name='热干面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='kung_fu_duck_leg_rice',
            field=models.IntegerField(default=0, verbose_name='功夫鸭腿饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='lemon_flavored_pork_offal_noodles',
            field=models.IntegerField(default=0, verbose_name='柠檬味猪杂面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='longjiang_pork_trotter_rice',
            field=models.IntegerField(default=0, verbose_name='隆江猪脚饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='nanchang_mixed_noodles',
            field=models.IntegerField(default=0, verbose_name='南昌拌面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='original_pork_offal_noodles',
            field=models.IntegerField(default=0, verbose_name='原味猪杂面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='original_seafood_pork_offal_noodles',
            field=models.IntegerField(default=0, verbose_name='原味海鲜猪杂面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='pork_mince_with_eggplant_over_rice',
            field=models.IntegerField(default=0, verbose_name='肉沫茄子盖饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='pork_stew_rice',
            field=models.IntegerField(default=0, verbose_name='卤肉饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rose_sauce_chicken_rice',
            field=models.IntegerField(default=0, verbose_name='玫瑰豉油鸡饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='salivating_chicken',
            field=models.IntegerField(default=0, verbose_name='口水鸡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='salt_baked_chicken_leg_rice',
            field=models.IntegerField(default=0, verbose_name='盐焗鸡腿饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='sausage_fried_with_dried_radish',
            field=models.IntegerField(default=0, verbose_name='腊肠炒萝卜干'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='scallion_oil_mixed_noodles',
            field=models.IntegerField(default=0, verbose_name='葱油拌面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='seaweed_braised_chicken',
            field=models.IntegerField(default=0, verbose_name='海苔碎焖鸡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='seaweed_braised_chicken_with_chicken_steak',
            field=models.IntegerField(default=0, verbose_name='海苔焖鸡拼鸡扒'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='secret_recipe_chicken_steak_rice',
            field=models.IntegerField(default=0, verbose_name='秘制鸡排饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='sichuan_style_spicy_fish_noodles',
            field=models.IntegerField(default=0, verbose_name='川香麻辣口味五谷鱼粉'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='signature_beggars_chicken',
            field=models.IntegerField(default=0, verbose_name='招牌叫花鸡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='signature_chicken_leg_rice',
            field=models.IntegerField(default=0, verbose_name='招牌鸡腿饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='signature_roast_duck_rice',
            field=models.IntegerField(default=0, verbose_name='招牌烧鸭饭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='sour_cabbage_beef_noodles',
            field=models.IntegerField(default=0, verbose_name='酸菜牛肉面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='sour_cabbage_wonton',
            field=models.IntegerField(default=0, verbose_name='酸菜抄手'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='spicy_shrimp',
            field=models.IntegerField(default=0, verbose_name='香辣虾'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='spicy_wonton',
            field=models.IntegerField(default=0, verbose_name='麻辣抄手'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='tomato_flavored_pork_offal_noodles',
            field=models.IntegerField(default=0, verbose_name='番茄味猪杂面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='xinjiang_style_large_plate_chicken',
            field=models.IntegerField(default=0, verbose_name='新疆大盘鸡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='xinjiang_style_large_plate_chicken_with_coca_cola_chicken',
            field=models.IntegerField(default=0, verbose_name='新疆大盘鸡拼可乐鸡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='zhanjiang_boiled_chicken_rice',
            field=models.IntegerField(default=0, verbose_name='湛江白切鸡饭'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mooddata',
            name='Dish',
            field=models.CharField(max_length=50, verbose_name='菜品'),
        ),
        migrations.AlterField(
            model_name='mooddata',
            name='angrie',
            field=models.IntegerField(verbose_name='生气'),
        ),
        migrations.AlterField(
            model_name='mooddata',
            name='dehydratie',
            field=models.IntegerField(verbose_name='脱水'),
        ),
        migrations.AlterField(
            model_name='mooddata',
            name='depressie',
            field=models.IntegerField(verbose_name='抑郁'),
        ),
        migrations.AlterField(
            model_name='mooddata',
            name='excitie',
            field=models.IntegerField(verbose_name='兴奋'),
        ),
        migrations.AlterField(
            model_name='mooddata',
            name='happie',
            field=models.IntegerField(verbose_name='开心'),
        ),
        migrations.AlterField(
            model_name='mooddata',
            name='unwellie',
            field=models.IntegerField(verbose_name='不适'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='alootikki',
            field=models.IntegerField(verbose_name='炸土豆饼'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='chholebature',
            field=models.IntegerField(verbose_name='炒饼'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='chillypaneer',
            field=models.IntegerField(verbose_name='辣椒炒干酪'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='chocolates',
            field=models.IntegerField(verbose_name='巧克力'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='cost',
            field=models.IntegerField(verbose_name='花费'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='count',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='dosa',
            field=models.IntegerField(verbose_name='薄饼'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='garlicbread',
            field=models.IntegerField(verbose_name='蒜香面包'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='ham',
            field=models.IntegerField(verbose_name='火腿'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='icecream',
            field=models.IntegerField(verbose_name='冰激凌'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='idli',
            field=models.IntegerField(verbose_name='印度小圆饼'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='juices',
            field=models.IntegerField(verbose_name='果汁'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=256, verbose_name='餐厅名称'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='noodles',
            field=models.IntegerField(verbose_name='面条'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='pasta',
            field=models.IntegerField(verbose_name='意大利面'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='pastries',
            field=models.IntegerField(verbose_name='蛋糕'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rajmachawal',
            field=models.IntegerField(verbose_name='拉吉玛饭'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='softdrinks',
            field=models.IntegerField(verbose_name='软饮料'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='springroll',
            field=models.IntegerField(verbose_name='春卷'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='tea',
            field=models.IntegerField(verbose_name='茶'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='vadapao',
            field=models.IntegerField(verbose_name='炸馅饼'),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='cost',
            field=models.IntegerField(verbose_name='花费'),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='distance',
            field=models.IntegerField(verbose_name='距离'),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='yesno',
            field=models.IntegerField(verbose_name='是否'),
        ),
    ]
