# Generated by Django 3.2.25 on 2024-12-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody_1', '0002_auto_20241223_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='alootikki',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='american_coca_cola_chicken',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='chholebature',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='chillypaneer',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='chocolates',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='curry_chicken_rice',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='dosa',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='garlicbread',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='ham',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='icecream',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='idli',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='juices',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='noodles',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='pastries',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='rajmachawal',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='seaweed_braised_chicken_with_chicken_steak',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='softdrinks',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='springroll',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='tea',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='vadapao',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='xinjiang_style_large_plate_chicken',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='xinjiang_style_large_plate_chicken_with_coca_cola_chicken',
        ),
    ]
