# Generated by Django 3.2.25 on 2024-12-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody_1', '0003_auto_20241224_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='sichuan_style_spicy_fish_noodles',
            new_name='sichuan_style_spicy_five_grain_fish_noodles',
        ),
    ]
