# Generated by Django 3.2.25 on 2024-12-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody_1', '0004_rename_sichuan_style_spicy_fish_noodles_restaurants_sichuan_style_spicy_five_grain_fish_noodles'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='curry_chicken_rice',
            field=models.IntegerField(default=0, verbose_name='咖喱鸡饭'),
            preserve_default=False,
        ),
    ]
