# Generated by Django 3.2.25 on 2024-12-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody_1', '0005_restaurants_curry_chicken_rice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='signature_beggars_chicken',
            new_name='signature_beggar_chicken',
        ),
    ]
